name: tasty-process
version: 0.1.0.1
github: "HEIGE-PCloud/tasty-process"
license: GPL-2
author: "PCloud"
maintainer: "heige.pcloud@outlook.com"
copyright: "(c) 2024 PCloud"
category: Testing
synopsis: Test execution of external processes with Tasty

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/HEIGE-PCloud/tasty-process#readme>

pvp-bounds: both

dependencies:
  - base >= 4.7 && < 5
  - tasty >= 1.4 && < 1.6
  - process >= 1.6.4 && < 1.7
  - deepseq >= 1.4 && < 1.6
  - async >= 2.2.5 && < 2.3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  tasty-process-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty-process
      - tasty-expected-failure
    build-tool-depends:
      - test-executable-echo
      - test-executable-exitcode
      - test-executable-simple
      - test-executable-sleep
    

executables:
  test-executable-simple:
    main: Main.hs
    source-dirs: test/executables/simple
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty-process
  test-executable-echo:
    main: Main.hs
    source-dirs: test/executables/echo
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty-process
  test-executable-sleep:
    main: Main.hs
    source-dirs: test/executables/sleep
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty-process
  test-executable-exitcode:
    main: Main.hs
    source-dirs: test/executables/exitcode
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty-process
