name:                tasty-process
version:             0.1.0.0
github:              "HEIGE-PCloud/tasty-process"
license:             GPL-2.0
author:              "PCloud"
maintainer:          "heige.pcloud@outlook.com"
copyright:           "(c) 2024 PCloud"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HEIGE-PCloud/tasty-process#readme>

dependencies:
- base >= 4.7 && < 5
- tasty
- process
- deepseq
- async

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  tasty-process-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F
    - -pgmF=tasty-autocollect
    build-tools:
    - tasty-autocollect:tasty-autocollect
    dependencies:
    - tasty-process
    - tasty-autocollect

executables:
  test-executable:
    main:                Main.hs
    source-dirs:         test/executable
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty-process
