name: CI
on: [push, pull_request]

jobs:
  build:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        ghc-version: ["9.8", "9.6", "9.4", "9.2", "9.0"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          enable-stack: true
          stack-version: "latest"

      - name: Test
        run: stack test --compiler ghc-${{ matrix.ghc-version }}
