name: CI
on: [push, pull_request]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/run-fourmolu@v9

  build:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    needs: fourmolu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc-version: ["9.8", "9.6", "9.4"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          enable-stack: true
          stack-version: "latest"
      - name: Build
        run: stack build --test --no-run-tests --compiler ghc-${{ matrix.ghc-version }}
      - name: Test
        run: stack test --compiler ghc-${{ matrix.ghc-version }}
